INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Prato Friso Ouro','Prato friso ouro em porcelana Schmidt','https://res.cloudinary.com/dykafjv63/image/upload/prato-friso-ouro.webp','PRATOS'),
	 ('Prato Prisma','Prato prisma em porcelana Schimidt','https://res.cloudinary.com/dykafjv63/image/upload/prato-prisma.webp','PRATOS'),
	 ('Prato Quadrado','Prato quadrado em porcelana Schmidt','https://res.cloudinary.com/dykafjv63/image/upload/prato-quadrado.jpg','PRATOS'),
	 ('Prato Branco Liso','Prato branco liso modelo 073 em porcelana branca Schmidt','https://res.cloudinary.com/dykafjv63/image/upload/prato-branco-liso.jpg','PRATOS'),
	 ('Prato modelo Beatriz','Prato branco modelo Beatriz','https://res.cloudinary.com/dykafjv63/image/upload/prato-modelo-beatriz.jpg','PRATOS'),
	 ('Prato para massas Beatriz','Prato para massas/risoto modelo beatriz','https://res.cloudinary.com/dykafjv63/image/upload/prato-massas-beatriz.jpg','PRATOS'),
	 ('Prato de bolo em Louça','Prato de bolo em louça com pé tamanho 34,0cm/d','https://res.cloudinary.com/dykafjv63/image/upload/prato-bolo-louca.webp','PRATOS'),
	 ('Prato de bolo em Louça','Prato de bolo em Louça com pé tamanho 26,0cm/d','https://res.cloudinary.com/dykafjv63/image/upload/prato-bolo-louca-26-cm.webp','PRATOS'),
	 ('Taça de vinho Barone','Taça para vinho modelo Barone 490ml','https://res.cloudinary.com/dykafjv63/image/upload/Taca-de-vinho-barone.webp','COPOS'),
	 ('Taça de Vinho Imperatriz','Taça de vinho modelo Imperatriz 600ml. Utilizada para Aperol e Vinhos','https://res.cloudinary.com/dykafjv63/image/upload/Taca-de-vinho-imperatriz.webp','COPOS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Taça de vinho/Água Bistrô','Taça de vinho/Água modelo Bistrô ref.914 300ml','https://res.cloudinary.com/dykafjv63/image/upload/Taca-de-vinho-bistro.webp','COPOS'),
	 ('Taça de Gin','Taça para Gin 600ml','https://res.cloudinary.com/dykafjv63/image/upload/Taca-de-gin.webp','COPOS'),
	 ('Taça de champagne Bistrô','Taça de champagne modelo Bistrô ref.916 186ml','https://res.cloudinary.com/dykafjv63/image/upload/Taca-de-champagne-bistro.webp','COPOS'),
	 ('Taça de Champagne Gallant','Taça de champagne modelo Gallant 180ml','https://res.cloudinary.com/dykafjv63/image/upload/Taca-de-champagne-gallant.jpg','COPOS'),
	 ('Taça de Dry Martini','Taça alta para Dry Martini 250ml','https://res.cloudinary.com/dykafjv63/image/upload/taca-de-dry-martini.webp','COPOS'),
	 ('Taça de licor de Cristal','Taça de licor de cristal 60ml','https://res.cloudinary.com/dykafjv63/image/upload/taca-de-licor-cristal.webp','COPOS'),
	 ('Copo Ilhabela','Copo para caipirinha e drink´s modelo Ilhabela 350ml','https://res.cloudinary.com/dykafjv63/image/upload/copo-ilhabela.webp','COPOS'),
	 ('Copo Longdrink','Copo Longdrink de 300ml para chopp, Água, refrigerante, sucos e outros','https://res.cloudinary.com/dykafjv63/image/upload/copo-longdrink.webp','COPOS'),
	 ('Tulipinha para Cerveja','Copo para cerveja tulipinha de 200ml','https://res.cloudinary.com/dykafjv63/image/upload/tulipinha-para-cerveja.webp','COPOS'),
	 ('Copo Stylo 802','Copo linha Stylo ref.802','https://res.cloudinary.com/dykafjv63/image/upload/copo-stylo.webp','COPOS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Copo Stylo 801','Copo linha Stylo ref.801','https://res.cloudinary.com/dykafjv63/image/upload/copo-stylo-801.webp','COPOS'),
	 ('Copo Accent Rock''s 374','Copo universal para diversos tipos de bebidas','https://res.cloudinary.com/dykafjv63/image/upload/copo-accent-rock-374.webp','COPOS'),
	 ('Copo para Whisky OTR','Copo para Whisky On The Rocks 265ml','https://res.cloudinary.com/dykafjv63/image/upload/copo-para-whisky-otr.webp','COPOS'),
	 ('Copo de Shot Olé','Copo de Shot aperitivo 60ml','https://res.cloudinary.com/dykafjv63/image/upload/copo-shot-ole.webp','COPOS'),
	 ('Copo caninha','Copo para caninha 100ml','https://res.cloudinary.com/dykafjv63/image/upload/copo-caninha.webp','COPOS'),
	 ('Copo Vodka/Whisky','Copo para Vodka ou Whisky dose 70ml','https://res.cloudinary.com/dykafjv63/image/upload/copo-vodka-whisky.webp','COPOS'),
	 ('Taça para Sobremesa','Taça para sobremesa de vidro','https://res.cloudinary.com/dykafjv63/image/upload/taca-para-sobremesa.webp','COPOS'),
	 ('Taça sobremesa Fiesta','Taça para sobremesa modelo Fiesta ref.736','https://res.cloudinary.com/dykafjv63/image/upload/taca-sobremesa-fiesta.webp','COPOS'),
	 ('Taça Sobremesa Selection','Taça de sobremesa modelo Selection ref.840','https://res.cloudinary.com/dykafjv63/image/upload/taca-sobremesa-selection.webp','COPOS'),
	 ('Taça Coquetel Cisper','Taça para coquetel, finger food, etc. ref.503','https://res.cloudinary.com/dykafjv63/image/upload/taca-coquetel-cisper.webp','COPOS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Rechaud 2 Cubas','Rechaud em banho maria de inox com 2 cubas de 4L cada.','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-2-cubas.webp','RECHAUD'),
	 ('Rechaud cuba inteira','Rechaud em banho maria de inox com cuba inteira 9L.','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-cuba-inteira.webp','RECHAUD'),
	 ('Rechaud Panela inox 8L','Rechaud panela em banho maria de inox com capacidade de 8L.','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-panela-inox.webp','RECHAUD'),
	 ('Rechaud Panela 5L','Rechaud panela com tampa de vidro de 5L','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-panela.webp','RECHAUD'),
	 ('Rechaud Panela molho inox 1.5L','Rechaud panela para molho em banho maria de inox com capacidade de 1.5L','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-panela-molho-inox.webp','RECHAUD'),
	 ('Rechaud Panela Cerâmica','Rechaud em cerâmica esmaltada com chapa difusora capacidade 5L','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-panela-cerâmica.webp','RECHAUD'),
	 ('Rechaud de pirex retangular','Rechaud em inox com pirex de vidro e tampa','https://res.cloudinary.com/dykafjv63/image/upload/RechTaça de vinho/Água Bistrôaud-pirex-retangular.webp','RECHAUD'),
	 ('Rechaud Chapa Inox','Rechaud com chapa difusora em inox','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-chapa-inox.webp','RECHAUD'),
	 ('Rechaud para Salgados','Rechaud com pirex redondo em base de inox e bandeja para servir salgadinhos.Acompanha 1 vela de rechaud.','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-salgados.webp','RECHAUD'),
	 ('Rechaud Grade Dourado','Rechaud rústico grade para travessas grande','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-grade-dourado.webp','RECHAUD');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Rechaud para Bule','Rechaud com vela para bule','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-bule.webp','RECHAUD'),
	 ('Garrafa Térmica em inox 1,8L','Garrafa térmica de 1,8L em inox Invicta com ampola de vidro','https://res.cloudinary.com/dykafjv63/image/upload/Garrafa-térmica-inox-18L-invicta.webp','GARRAFAS'),
	 ('Garrafa Térmica inox 1,8L','Garrafa térmica inox 1,8L com ampola de vidro','https://res.cloudinary.com/dykafjv63/image/upload/Garrafa-térmica-inox-1_OaCxeJu.8L.webp','GARRAFAS'),
	 ('Garrafa Térmica inox 2,5L','Garrafa térmica inox 2,5l sem ampola','https://res.cloudinary.com/dykafjv63/image/upload/Garrafa-térmica-inox-2_ODnsjo9.5L.webp','GARRAFAS'),
	 ('Garrafa Térmica inox 3L','Garrafa térmica inox 3L sem ampola','https://res.cloudinary.com/dykafjv63/image/upload/Garrafa-térmica-inox-3L.webp','GARRAFAS'),
	 ('Jarra Térmica inox','Jarra térmica inox 1,5L com ampola de vidro','https://res.cloudinary.com/dykafjv63/image/upload/Jarra-térmica-inox.webp','GARRAFAS'),
	 ('Talher Classic 493','Talher de luxo HÚrcules modelo Classique 493 em aþo inox bordado','https://res.cloudinary.com/dykafjv63/image/upload/Talher-classic-493.webp','TALHERES'),
	 ('Talher ISIS','Talher importado PortuguÛs modelo ISIS em aþo inox','https://res.cloudinary.com/dykafjv63/image/upload/Talher-isis.webp','TALHERES'),
	 ('Talher Urca 1480','Talher HÚrcules modelo Urca 1480 em aþo inox','https://res.cloudinary.com/dykafjv63/image/upload/Talher-Urca-1480.webp','TALHERES'),
	 ('Talheres América','Talher em inox modelo América','https://res.cloudinary.com/dykafjv63/image/upload/Talheres-america.webp','TALHERES');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Talher Leme 300','Talher HÚrcules modelo Leme 300 em aþo inox','https://res.cloudinary.com/dykafjv63/image/upload/Talheres-leme-300.webp','TALHERES'),
	 ('Talher churrasco Polywood','Talher para churrasco Tramontina modelo polywood com cabo em madeiro','https://res.cloudinary.com/dykafjv63/image/upload/Talher-churrasco-polywood.webp','TALHERES'),
	 ('Garfo Sobremesa Moniz','Garfo de Sobremesa modelo Moniz','https://res.cloudinary.com/dykafjv63/image/upload/Garfo-sobremesa-moniz.webp','TALHERES'),
	 ('Mini Garfo aperitivo','Garfo para mini refeições','https://res.cloudinary.com/dykafjv63/image/upload/Mini-garfo-aperitivo.webp','TALHERES'),
	 ('Espátula cabo marfim','Espátula para pastas com cabo de plástico marfim Tramontina','https://res.cloudinary.com/dykafjv63/image/upload/Espatula-cabo-marfim.webp','TALHERES'),
	 ('Suqueira de Vidro','Suqueira em vidro de 5L','https://res.cloudinary.com/dykafjv63/image/upload/Suqueira-vidro.webp','VIDROS'),
	 ('Suqueira Cristal','Suqueira Cristal 5L','https://res.cloudinary.com/dykafjv63/image/upload/Suqueira-cristal.webp','VIDROS'),
	 ('Balde de gelo cristal','Balde de gelo pequeno 1L cristal com alça de inox e pegador de inox','https://res.cloudinary.com/dykafjv63/image/upload/Balde-gelo.webp','VIDROS'),
	 ('Meleira de vidro com inox','Meleira de vidro com tampa em inox com corta pingo e capacidade para 150ml','https://res.cloudinary.com/dykafjv63/image/upload/Meleira-vidro.webp','VIDROS'),
	 ('Jarra de suco Nobile 1.5L','Jarra de suco Nobile facetada 1.5L Cisper','https://res.cloudinary.com/dykafjv63/image/upload/Jarra-de-suco-nobile.webp','VIDROS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Boleira em vidro com pé','Boleira em vidro com pé, cúpula de acrílico. Tamanho 26,0x10,5cm','https://res.cloudinary.com/dykafjv63/image/upload/Boleira-vidro-pe.webp','VIDROS'),
	 ('Prato de bolo sem tampa','Prato de bolo em vidro com pé sem cúpula tamanho 26,0x10,5cm','https://res.cloudinary.com/dykafjv63/image/upload/Prato-bolo-sem-tampa.webp','VIDROS'),
	 ('Saladeira Chapéu','Saladeira de vidro chapéu grande','https://res.cloudinary.com/dykafjv63/image/upload/Saladeira-chapeu.webp','VIDROS'),
	 ('Saladeira vidro frisada Madri','Saladeira de vidro frisada Madri grande','https://res.cloudinary.com/dykafjv63/image/upload/Saladeira-vidro-frisada-madri.webp','VIDROS'),
	 ('Compoteira com tampa','Compoteira grande com tampa de vidro pés baixo','https://res.cloudinary.com/dykafjv63/image/upload/Compoteira-tampa.webp','VIDROS'),
	 ('Compoteira sem tampa','Compoteira sem tampa de vidro de pé alto','https://res.cloudinary.com/dykafjv63/image/upload/Compoteira-sem-tampa.webp','VIDROS'),
	 ('Saladeira grande Taça','Saladeira em vidro formato em taça grande 5L','https://res.cloudinary.com/dykafjv63/image/upload/Saladeira-grande-taca.webp','VIDROS'),
	 ('Saladeira de vidro grande','Saladeira com recipiente para gelo','https://res.cloudinary.com/dykafjv63/image/upload/Saladeira-vidro-grande.webp','VIDROS'),
	 ('Prato de bolo Cristal com pé','Prato de bolo cristal com pé tamanho 26x10,5cm de diamêtro.','https://res.cloudinary.com/dykafjv63/image/upload/Prato-bolo-cristal-pe.webp','TRAVESSAS'),
	 ('Travessa de Cristal Dragon','Travessa de cristal com pé retangular modelo Dragon.
34,0x15,0x10,5cm','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-Cristal-Dragon.webp','TRAVESSAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Prato de bolo cristal Janine','Prato de bolo cristal modelo Janine com pé tamanho 29,5x19,5x10,5cm','https://res.cloudinary.com/dykafjv63/image/upload/Prato-bolo-cristal-Janine.webp','TRAVESSAS'),
	 ('Travessa baixa de cristal Dragon','Travessa de cristal baixa modelo Dragon. Tamanho: 34,0x15,0x2,5cm','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-baixa-cristal-dragon.webp','TRAVESSAS'),
	 ('Travessa em Inox','Travessa oval de diversos tamanhos de inox 56,45 e 30cm','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-inox.webp','TRAVESSAS'),
	 ('Travessa Redonda','Travessa redonda de inox com tampa de vidro 4.5L','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-redonda.webp','TRAVESSAS'),
	 ('Travessa para peixe','Travessa de inox oval para peixada','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-peixe.webp','TRAVESSAS'),
	 ('Travessa de arroz com tampa','Travessa de arroz com tampa de inox','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-arroz-tampa.webp','TRAVESSAS'),
	 ('Bandeja de garçom','Bandeja de garçom inox de 40cm','https://res.cloudinary.com/dykafjv63/image/upload/Bandeja-garcom.webp','TRAVESSAS'),
	 ('Bandeja redonda rasa','Bandeja redonda rasa em inox','https://res.cloudinary.com/dykafjv63/image/upload/Bandeja-redonda-rasa.webp','TRAVESSAS'),
	 ('Travessa Redonda','Travessa redonda para biscoito em inox','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-redonda-inox.webp','TRAVESSAS'),
	 ('Bandeja retangular','Bandeja retangular de inox','https://res.cloudinary.com/dykafjv63/image/upload/Bandeja-retangular.webp','TRAVESSAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Pilter para salada','Pilter para salada em inox','https://res.cloudinary.com/dykafjv63/image/upload/Pilter-salada.webp','TRAVESSAS'),
	 ('Expositor de 3 bandejas','Expositor com 3 bandejas ajustáveis de vidro','https://res.cloudinary.com/dykafjv63/image/upload/Expositor-3-bandejas.webp','TRAVESSAS'),
	 ('Bandeja de vidro redonda','Bandeja de vidro redonda com pés em inox diversos tamanhos','https://res.cloudinary.com/dykafjv63/image/upload/Bandeja-vidro-redonda.webp','TRAVESSAS'),
	 ('Bandeja quadrada de vidro','Bandeja quadrada de vidro com pés em inox diversos tamanhos','https://res.cloudinary.com/dykafjv63/image/upload/Bandeja-quadrada-vidro.webp','TRAVESSAS'),
	 ('Bandeja retangular de vidro','Bandeja retangular de vidro com pés em inox','https://res.cloudinary.com/dykafjv63/image/upload/Bandeja-retangular-vidro.webp','TRAVESSAS'),
	 ('Bandeja de vidro redonda giratória','Bandeja de vidro redonda giratória','https://res.cloudinary.com/dykafjv63/image/upload/Bandeja-vidro-redonda-giratoria.webp','TRAVESSAS'),
	 ('Lâmina de vidro redonda','Lâmina redonda de vidro 40cm','https://res.cloudinary.com/dykafjv63/image/upload/Lamina-vidro-redonda.webp','TRAVESSAS'),
	 ('Travessa de cerâmica','Travessa cerâmica oval 35cm','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-ceramica.webp','TRAVESSAS'),
	 ('Travessa cerâmica retangular','Travessa cerâmica retangular 35cm','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-ceramica-retangular.webp','TRAVESSAS'),
	 ('Champanheira de mesa','Champanheira para 3 garrafas','https://res.cloudinary.com/dykafjv63/image/upload/Champanheira-de-mesa.webp','INOX');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Suporte para balde de champagne','Suporte em inox para balde de champagne','https://res.cloudinary.com/dykafjv63/image/upload/Suporte-para-balde-de-champagne.webp','INOX'),
	 ('Sopeira','Sopeira em inox 4L','https://res.cloudinary.com/dykafjv63/image/upload/Sopeira.webp','INOX'),
	 ('Molheira','Molheira em inox','https://res.cloudinary.com/dykafjv63/image/upload/Molheira.webp','INOX'),
	 ('Bowls de Inox','Bowls de inox Grande e Médio','https://res.cloudinary.com/dykafjv63/image/upload/Bowls-de-inox.webp','INOX'),
	 ('Petisqueira','Petisqueira em inox com 3 divisões','https://res.cloudinary.com/dykafjv63/image/upload/Petisqueira.webp','INOX'),
	 ('Porta guardanapos em inox','Porta guardanapos em inox','https://res.cloudinary.com/dykafjv63/image/upload/Porta-guardanapos.webp','INOX'),
	 ('Mantegueira','Mantegueira em inox','https://res.cloudinary.com/dykafjv63/image/upload/Mantegueira.webp','INOX'),
	 ('Bule de café pequeno','Bule de café pequeno','https://res.cloudinary.com/dykafjv63/image/upload/Bule-de-cafe.webp','INOX'),
	 ('Bule de café grande','Bule de café grande','https://res.cloudinary.com/dykafjv63/image/upload/Bule-de-cafe-grande.webp','INOX'),
	 ('Balde de champagne','Balde em inox de champagne','https://res.cloudinary.com/dykafjv63/image/upload/Balde-de-champagne.webp','INOX');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Leiteira','Leiteira em inox','https://res.cloudinary.com/dykafjv63/image/upload/Leiteira.webp','INOX'),
	 ('Bule de chá','Bule de chá em inox','https://res.cloudinary.com/dykafjv63/image/upload/Bule-de-cha.webp','INOX'),
	 ('Galheteiro','Galheteiro para azeite e vinagre','https://res.cloudinary.com/dykafjv63/image/upload/Galheteiro.webp','INOX'),
	 ('Balde de Gelo','Balde de gelo pequeno em inox','https://res.cloudinary.com/dykafjv63/image/upload/Balde-de-gelo.webp','INOX'),
	 ('Açucareiro','Açucareiro em inox','https://res.cloudinary.com/dykafjv63/image/upload/Acucareiro.webp','INOX'),
	 ('Colher Chinesa','Colher para Finger Food de porcelana branca 14cm e 20ml','https://res.cloudinary.com/dykafjv63/image/upload/Colher-chinesa.webp','LOUCAS'),
	 ('Pote Oriental','Pote oriental quadrado de louþa para mini refeiþ§es 110ml Schimidt. 9,00x3,00cm','https://res.cloudinary.com/dykafjv63/image/upload/Pote-oriental.webp','LOUCAS'),
	 ('Tigela golden baixa','Tigela quadrada baixa em louça para mini refeições. 9,00x3,00cm','https://res.cloudinary.com/dykafjv63/image/upload/Tigela-golden-baixa.webp','LOUCAS'),
	 ('Tigela Retangular com alça','Tigela retangular em louça com alça para mini refeições. 10,5x7,00x2,5cm','https://res.cloudinary.com/dykafjv63/image/upload/Tigela-retangular-com-alca.webp','LOUCAS'),
	 ('Pote Pirâmide','Pote pirâmide para mini refeições 110ml. 9,00x3,5cm','https://res.cloudinary.com/dykafjv63/image/upload/Pote-piramide.webp','LOUCAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Bowls pequeno de 240ml','Bowl de louça pequeno 240ml','https://res.cloudinary.com/dykafjv63/image/upload/Bowls-pequeno-240.webp','LOUCAS'),
	 ('Copo de caldo de feijão','Copo de louça para caldo de feijão 100ml.','https://res.cloudinary.com/dykafjv63/image/upload/Copo-caldo-feijao.webp','LOUCAS'),
	 ('Tigela de louça','Tigela de louça branca 400ml.','https://res.cloudinary.com/dykafjv63/image/upload/Tigela-louca.webp','LOUCAS'),
	 ('Ramequin de louça','Ramequin de louça pequeno 80ml. 4,00cm','https://res.cloudinary.com/dykafjv63/image/upload/Ramequin-louca.webp','LOUCAS'),
	 ('Mantegueira','Mantegueira pequena','https://res.cloudinary.com/dykafjv63/image/upload/Mantegueira.webp','LOUCAS'),
	 ('Sanduicheira de louça','Sanduicheira de louça retangular. 18cm','https://res.cloudinary.com/dykafjv63/image/upload/Sanduicheira-de-louca.webp','LOUCAS'),
	 ('Travessa Guarnição','Travessa oval para guarnições pequena. 17cm','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-guarnicao.webp','LOUCAS'),
	 ('Pote para pastas','Pote de louça para pastas e patê','https://res.cloudinary.com/dykafjv63/image/upload/Pote-pastas.webp','LOUCAS'),
	 ('Açucareiro em louça','Açucareiro em louça sem colher','https://res.cloudinary.com/dykafjv63/image/upload/Acucareiro-louca.webp','LOUCAS'),
	 ('Petisqueira redonda','Petisqueira de louça redonda','https://res.cloudinary.com/dykafjv63/image/upload/Petisqueira-redonda.webp','LOUCAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Caneca de vinho','Caneca de vinho de 300ml','https://res.cloudinary.com/dykafjv63/image/upload/Caneca-vinho.jpg','LOUCAS'),
	 ('Mini caldeirão','Mini caldeirão esmaltado para feijão ou caldos. 500ml','https://res.cloudinary.com/dykafjv63/image/upload/Mini-caldeirao.webp','LOUCAS'),
	 ('Tigela cerâmica','Tigela cerâmica rústica de 400ml','https://res.cloudinary.com/dykafjv63/image/upload//Tigela-ceramica.webp','LOUCAS'),
	 ('Xícara de café vera cruz','Xícara de café vera cruz branca simples','https://res.cloudinary.com/dykafjv63/image/upload/Xicara-cafe-vera-cruz.webp','XICARAS'),
	 ('Xícara de café friso ouro','Xícara de café friso ouro vera cruz','https://res.cloudinary.com/dykafjv63/image/upload/Xicara-cafe-friso-ouro.webp','XICARAS'),
	 ('Xícara de café friso ouro','Xícara de café friso ouro Schimidt','https://res.cloudinary.com/dykafjv63/image/upload/Xicara-cafe-friso-ouro-schimidt.jpg','XICARAS'),
	 ('Xícara de chá friso ouro','Xícara de chá friso ouro Schimidt','https://res.cloudinary.com/dykafjv63/image/upload/Xicara-de-cha-friso-ouro.jpg','XICARAS'),
	 ('Xícara de chá friso ouro','Xícara de chá friso ouro com fino acabamento em fio de ouro em sua borda e pires.','https://res.cloudinary.com/dykafjv63/image/upload/xicara-cha-friso-ouro.jpg','XICARAS'),
	 ('Xícara de chá 177','Xícara de chá modelo 177 branca simples','https://res.cloudinary.com/dykafjv63/image/upload/Xicara-de-cha-177.jpg','XICARAS'),
	 ('Xícara de chá Prisma','Xícara de chá Prisma branca','https://res.cloudinary.com/dykafjv63/image/upload/Xicara-de-cha-prisma.webp','XICARAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Bule de café Prisma','Bule de café Schimidt modelo prisma em louça branca com fino acabamento pequeno e grande','https://res.cloudinary.com/dykafjv63/image/upload/Bule-de-cafe-prisma.jpg','XICARAS'),
	 ('Bule de chá Prisma','Bule de chá  Schimidt modelo prisma em louça branca com fino acabamento','https://res.cloudinary.com/dykafjv63/image/upload/Bule-de-cha-prisma.jpg','XICARAS'),
	 ('Açucareiro Prisma','Açucareiro Schimidt modelo prisma em louça branca com fino acabamento.Pequeno e grande','https://res.cloudinary.com/dykafjv63/image/upload/Acucareiro-prisma.jpg','XICARAS'),
	 ('Rechaud panela em prata','Rechaud panela em prata 10L','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-panela-prata.webp','PRATARIA'),
	 ('Rechaud Panela em prata','Rechaud panela em prata com banho maria 6L','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-panela-prata-6L.webp','PRATARIA'),
	 ('Rechaud molho em prata','Rechaud para molho em prata 2L','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-molho-prata.webp','PRATARIA'),
	 ('Rechaud chapa de prata','Rechaud chapa retangular de prata sem pirex','https://res.cloudinary.com/dykafjv63/image/upload/Rechaud-chapa-prata.webp','PRATARIA'),
	 ('Travessa oval em prata','Travessa oval em prata 45cm','https://res.cloudinary.com/dykafjv63/image/upload/Travessa-oval-prata.webp','PRATARIA'),
	 ('Samovar em prata','Samovar em prata 2L','https://res.cloudinary.com/dykafjv63/image/upload/Samovar-prata.webp','PRATARIA'),
	 ('Açucareiro em prata','Açucareiro em prata','https://res.cloudinary.com/dykafjv63/image/upload/Acucareiro-prata.webp','PRATARIA');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Bule de café em prata','Bule de café em prata pequeno','https://res.cloudinary.com/dykafjv63/image/upload/Bule-cafe-prata.webp','PRATARIA'),
	 ('Saladeira Madeira','Saladeira de madeira pequeno e grande','https://res.cloudinary.com/dykafjv63/image/upload/Saladeira-madeira.webp','MADEIRA'),
	 ('Tábua de frios grande','Tábua para frios redonda grande 40cm','https://res.cloudinary.com/dykafjv63/image/upload/Tabua-de-frios-grande.webp','MADEIRA'),
	 ('Tábua de frios pequena','Tábua para frios redonda pequena 25cm','https://res.cloudinary.com/dykafjv63/image/upload/Tabua-de-frios-pequena.webp','MADEIRA'),
	 ('Tábua pão a metro','Tábua para pão a metro de 80cm','https://res.cloudinary.com/dykafjv63/image/upload/Tabua-pao.webp','MADEIRA'),
	 ('Tábua de carne oval','Tábua para corte de carne oval','https://res.cloudinary.com/dykafjv63/image/upload/Tabua-carne-oval.webp','MADEIRA'),
	 ('Cesta de vime','Cesta de vime para pÒo. Diversos tamanhos','https://res.cloudinary.com/dykafjv63/image/upload/Cesta-vime.webp','MADEIRA'),
	 ('Cesta de vime com alþa','Cesta de vime para pÒo com alþa grande','https://res.cloudinary.com/dykafjv63/image/upload/Cesta-vime-alca.webp','MADEIRA'),
	 ('Caçarola de alumínio','Caçarola de alumínio Vigor industrial de 30 a 60L','https://res.cloudinary.com/dykafjv63/image/upload/Caçarola-de-aluminio.webp','PANELAS'),
	 ('Caldeirão de alumínio','Caldeirão de alumínio industrial Vigor de 40 a 65L','https://res.cloudinary.com/dykafjv63/image/upload/Caldeirao-de-aluminio.webp','PANELAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Panela de Inox','Caþarola de inox Brinox com capacidade de 8L','https://res.cloudinary.com/dykafjv63/image/upload/Panela-de-inox.webp','PANELAS'),
	 ('Panela de cerâmica','Caçarola de cerâmica esmaltada com capacidade de 5L','https://res.cloudinary.com/dykafjv63/image/upload/Panela-de-ceramica.webp','PANELAS'),
	 ('Toalha quadrada voal estampada','Toalha quadrada voal estampada','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-voal-estampada.webp','TOALHAS'),
	 ('Toalha quadrada estampada','Toalha quadrada estampada','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-estampada.webp','TOALHAS'),
	 ('Toalha Branca','Toalha quadrada e redonda branca','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-branca.webp','TOALHAS'),
	 ('Toalha quadrada vermelha','Toalha quadrada vermelha cetim ou tergal','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-vermelha.webp','TOALHAS'),
	 ('Toalha Preta','Toalha quadrada e pranchÒo preta','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-preta.webp','TOALHAS'),
	 ('Toalha quadrada azul','Toalha quadrada azul','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-azul-quadrada.webp','TOALHAS'),
	 ('Toalha ouro','Toalha quadrada e redonda ouro','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-ouro.webp','TOALHAS'),
	 ('Toalha quadrada nude','Toalha quadrada nude cetim','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-nude.webp','TOALHAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Toalha quadrada xadrez verde','Toalha quadrada xadrez verde','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-xadrez-verde.webp','TOALHAS'),
	 ('Toalha quadrada xadrez azul','Toalha quadrada xadrez azul','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-xadrez-azul.webp','TOALHAS'),
	 ('Tolha quadrada xadrez preta','Toalha quadrada xadrez preta','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-xadrez-preta.webp','TOALHAS'),
	 ('Toalha quadrada xadrez vermelha','Toalha quadrada xadrez vermelha','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-xadrez-vermelha.webp','TOALHAS'),
	 ('Toalha quadrada bolinha','Toalha quadrada bolinha','https://res.cloudinary.com/dykafjv63/image/upload/Toalha-quadrada-bolinha.webp','TOALHAS'),
	 ('Fogão de alta com 2 bocas','Fogão de alta pressão com pé 80cm de 2 bocas.Acompanha mangueira de alta pressão','https://res.cloudinary.com/dykafjv63/image/upload/Fogão-2-bocas.webp','EQUIPAMENTOS'),
	 ('Churrasqueira 200L','Churrasqueira de tambor de 200L com grade','https://res.cloudinary.com/dykafjv63/image/upload/Churrasqueira.webp','EQUIPAMENTOS'),
	 ('Tina para bebidas','Tinas para bebidas e gelo 120L','https://res.cloudinary.com/dykafjv63/image/upload/Tina-bebidas.webp','EQUIPAMENTOS');
