INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Prato Friso Ouro','Prato friso ouro em porcelana Schmidt','img/PRATOS/prato-friso-ouro_Rd71Jtk.webp','PRATOS'),
	 ('Prato Prisma','Prato prisma em porcelana Schimidt','img/PRATOS/prato-prisma_noZRRTQ.webp','PRATOS'),
	 ('Prato Quadrado','Prato quadrado em porcelana Schmidt','img/PRATOS/prato-quadrado.jpg','PRATOS'),
	 ('Prato Branco Liso','Prato branco liso modelo 073 em porcelana branca Schmidt','img/PRATOS/prato-branco-liso.jpg','PRATOS'),
	 ('Prato modelo Beatriz','Prato branco modelo Beatriz','img/PRATOS/prato-modelo-beatriz.jpg','PRATOS'),
	 ('Prato para massas Beatriz','Prato para massas/risoto modelo beatriz','img/PRATOS/prato-massas-beatriz.jpg','PRATOS'),
	 ('Prato de bolo em Louça','Prato de bolo em louça com pé tamanho 34,0cm/d','img/PRATOS/prato-bolo-louca_Z4xmcYn.webp','PRATOS'),
	 ('Prato de bolo em Louça','Prato de bolo em Louça com pé tamanho 26,0cm/d','img/PRATOS/prato-bolo-louca-26-cm_wYTQj8N.webp','PRATOS'),
	 ('Taça de vinho Barone','Taça para vinho modelo Barone 490ml','img/COPOS/Taca-de-vinho-barone_qolJWhK.webp','COPOS'),
	 ('Taça de Vinho Imperatriz','Taça de vinho modelo Imperatriz 600ml. Utilizada para Aperol e Vinhos','img/COPOS/Taca-de-vinho-imperatriz_7w5FPnY.webp','COPOS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Taça de vinho/Água Bistrô','Taça de vinho/Água modelo Bistrô ref.914 300ml','img/COPOS/Taca-de-vinho-bistro_AlMVukQ.webp','COPOS'),
	 ('Taça de Gin','Taça para Gin 600ml','img/COPOS/Taca-de-gin_Ue09Rkm.webp','COPOS'),
	 ('Taça de champagne Bistrô','Taça de champagne modelo Bistrô ref.916 186ml','img/COPOS/Taca-de-champagne-bistro_ymwjLp6.webp','COPOS'),
	 ('Taça de Champagne Gallant','Taça de champagne modelo Gallant 180ml','img/COPOS/Taca-de-champagne-gallant.jpg','COPOS'),
	 ('Taça de Dry Martini','Taça alta para Dry Martini 250ml','img/COPOS/taca-de-dry-martini_Hrmjrlu.webp','COPOS'),
	 ('Taça de licor de Cristal','Taça de licor de cristal 60ml','img/COPOS/taca-de-licor-cristal_Xd0qoSU.webp','COPOS'),
	 ('Copo Ilhabela','Copo para caipirinha e drink´s modelo Ilhabela 350ml','img/COPOS/copo-ilhabela_E0GBLzE.webp','COPOS'),
	 ('Copo Longdrink','Copo Longdrink de 300ml para chopp, Água, refrigerante, sucos e outros','img/COPOS/copo-longdrink_JFo5wUK.webp','COPOS'),
	 ('Tulipinha para Cerveja','Copo para cerveja tulipinha de 200ml','img/COPOS/tulipinha-para-cerveja_tzON4Ut.webp','COPOS'),
	 ('Copo Stylo 802','Copo linha Stylo ref.802','img/COPOS/copo-stylo_KzTwDbA.webp','COPOS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Copo Stylo 801','Copo linha Stylo ref.801','img/COPOS/copo-stylo-801_GHG52Wn.webp','COPOS'),
	 ('Copo Accent Rock''s 374','Copo universal para diversos tipos de bebidas','img/COPOS/copo-accent-rock-374_B6HsZfl.webp','COPOS'),
	 ('Copo para Whisky OTR','Copo para Whisky On The Rocks 265ml','img/COPOS/copo-para-whisky-otr_C6utgxZ.webp','COPOS'),
	 ('Copo de Shot Olé','Copo de Shot aperitivo 60ml','img/COPOS/copo-shot-ole_yeM46Dm.webp','COPOS'),
	 ('Copo caninha','Copo para caninha 100ml','img/COPOS/copo-caninha_38LQn42.webp','COPOS'),
	 ('Copo Vodka/Whisky','Copo para Vodka ou Whisky dose 70ml','img/COPOS/copo-vodka-whisky_yObiwzy.webp','COPOS'),
	 ('Taça para Sobremesa','Taça para sobremesa de vidro','img/COPOS/taca-para-sobremesa_5ahy3wv.webp','COPOS'),
	 ('Taça sobremesa Fiesta','Taça para sobremesa modelo Fiesta ref.736','img/COPOS/taca-sobremesa-fiesta_xc79heg.webp','COPOS'),
	 ('Taça Sobremesa Selection','Taça de sobremesa modelo Selection ref.840','img/COPOS/taca-sobremesa-selection_ahl5M0f.webp','COPOS'),
	 ('Taça Coquetel Cisper','Taça para coquetel, finger food, etc. ref.503','img/COPOS/taca-coquetel-cisper_kTtriKm.webp','COPOS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Rechaud 2 Cubas','Rechaud em banho maria de inox com 2 cubas de 4L cada.','img/RECHAUD/Rechaud-2-cubas_0iiJNq3.webp','RECHAUD'),
	 ('Rechaud cuba inteira','Rechaud em banho maria de inox com cuba inteira 9L.','img/RECHAUD/Rechaud-cuba-inteira_eKK358T.webp','RECHAUD'),
	 ('Rechaud Panela inox 8L','Rechaud panela em banho maria de inox com capacidade de 8L.','img/RECHAUD/Rechaud-panela-inox_kZlitBa.webp','RECHAUD'),
	 ('Rechaud Panela 5L','Rechaud panela com tampa de vidro de 5L','img/RECHAUD/Rechaud-panela_BvARq4D.webp','RECHAUD'),
	 ('Rechaud Panela molho inox 1.5L','Rechaud panela para molho em banho maria de inox com capacidade de 1.5L','img/RECHAUD/Rechaud-panela-molho-inox_A4g6OI0.webp','RECHAUD'),
	 ('Rechaud Panela Cerâmica','Rechaud em cerâmica esmaltada com chapa difusora capacidade 5L','img/RECHAUD/Rechaud-panela-cerâmica_gu48qIU.webp','RECHAUD'),
	 ('Rechaud de pirex retangular','Rechaud em inox com pirex de vidro e tampa','img/RECHAUD/RechTaça de vinho/Água Bistrôaud-pirex-retangular_KnUKtWw.webp','RECHAUD'),
	 ('Rechaud Chapa Inox','Rechaud com chapa difusora em inox','img/RECHAUD/Rechaud-chapa-inox_COLzxvA.webp','RECHAUD'),
	 ('Rechaud para Salgados','Rechaud com pirex redondo em base de inox e bandeja para servir salgadinhos.Acompanha 1 vela de rechaud.','img/RECHAUD/Rechaud-salgados_sNuTEAI.webp','RECHAUD'),
	 ('Rechaud Grade Dourado','Rechaud rústico grade para travessas grande','img/RECHAUD/Rechaud-grade-dourado_cvnwSKO.webp','RECHAUD');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Rechaud para Bule','Rechaud com vela para bule','img/RECHAUD/Rechaud-bule_pqe4XsS.webp','RECHAUD'),
	 ('Garrafa Térmica em inox 1,8L','Garrafa térmica de 1,8L em inox Invicta com ampola de vidro','img/GARRAFAS/Garrafa-térmica-inox-18L-invicta_rxmtgPX.webp','GARRAFAS'),
	 ('Garrafa Térmica inox 1,8L','Garrafa térmica inox 1,8L com ampola de vidro','img/GARRAFAS/Garrafa-térmica-inox-1_OaCxeJu.8L.webp','GARRAFAS'),
	 ('Garrafa Térmica inox 2,5L','Garrafa térmica inox 2,5l sem ampola','img/GARRAFAS/Garrafa-térmica-inox-2_ODnsjo9.5L.webp','GARRAFAS'),
	 ('Garrafa Térmica inox 3L','Garrafa térmica inox 3L sem ampola','img/GARRAFAS/Garrafa-térmica-inox-3L_Oz9mQLl.webp','GARRAFAS'),
	 ('Jarra Térmica inox','Jarra térmica inox 1,5L com ampola de vidro','img/GARRAFAS/Jarra-térmica-inox_kaH4dZJ.webp','GARRAFAS'),
	 ('Talher Classic 493','Talher de luxo HÚrcules modelo Classique 493 em aþo inox bordado','img/TALHERES/Talher-classic-493_kf4Jyw4.webp','TALHERES'),
	 ('Talher ISIS','Talher importado PortuguÛs modelo ISIS em aþo inox','img/TALHERES/Talher-isis_Rs2GDdp.webp','TALHERES'),
	 ('Talher Urca 1480','Talher HÚrcules modelo Urca 1480 em aþo inox','img/TALHERES/Talher-Urca-1480_rYlTJPh.webp','TALHERES'),
	 ('Talheres América','Talher em inox modelo América','img/TALHERES/Talheres-america_tiFdxhW.webp','TALHERES');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Talher Leme 300','Talher HÚrcules modelo Leme 300 em aþo inox','img/TALHERES/Talheres-leme-300_Ek6sLJp.webp','TALHERES'),
	 ('Talher churrasco Polywood','Talher para churrasco Tramontina modelo polywood com cabo em madeiro','img/TALHERES/Talher-churrasco-polywood_6OvlGBP.webp','TALHERES'),
	 ('Garfo Sobremesa Moniz','Garfo de Sobremesa modelo Moniz','img/TALHERES/Garfo-sobremesa-moniz_OBsSoDS.webp','TALHERES'),
	 ('Mini Garfo aperitivo','Garfo para mini refeições','img/TALHERES/Mini-garfo-aperitivo_wr7a6YJ.webp','TALHERES'),
	 ('Espátula cabo marfim','Espátula para pastas com cabo de plástico marfim Tramontina','img/TALHERES/Espatula-cabo-marfim_5GxN8Cs.webp','TALHERES'),
	 ('Suqueira de Vidro','Suqueira em vidro de 5L','img/VIDROS/Suqueira-vidro.webp','VIDROS'),
	 ('Suqueira Cristal','Suqueira Cristal 5L','img/VIDROS/Suqueira-cristal_iGLK5Id.webp','VIDROS'),
	 ('Balde de gelo cristal','Balde de gelo pequeno 1L cristal com alça de inox e pegador de inox','img/VIDROS/Balde-gelo_Ybyi9dt.webp','VIDROS'),
	 ('Meleira de vidro com inox','Meleira de vidro com tampa em inox com corta pingo e capacidade para 150ml','img/VIDROS/Meleira-vidro_yXVPxAJ.webp','VIDROS'),
	 ('Jarra de suco Nobile 1.5L','Jarra de suco Nobile facetada 1.5L Cisper','img/VIDROS/Jarra-de-suco-nobile_VxP2E9C.webp','VIDROS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Boleira em vidro com pé','Boleira em vidro com pé, cúpula de acrílico. Tamanho 26,0x10,5cm','img/VIDROS/Boleira-vidro-pe_yUtXgzU.webp','VIDROS'),
	 ('Prato de bolo sem tampa','Prato de bolo em vidro com pé sem cúpula tamanho 26,0x10,5cm','img/VIDROS/Prato-bolo-sem-tampa_a54vxfh.webp','VIDROS'),
	 ('Saladeira Chapéu','Saladeira de vidro chapéu grande','img/VIDROS/Saladeira-chapeu_7uKm1W3.webp','VIDROS'),
	 ('Saladeira vidro frisada Madri','Saladeira de vidro frisada Madri grande','img/VIDROS/Saladeira-vidro-frisada-madri_OOII3oO.webp','VIDROS'),
	 ('Compoteira com tampa','Compoteira grande com tampa de vidro pés baixo','img/VIDROS/Compoteira-tampa_T1YGdnT.webp','VIDROS'),
	 ('Compoteira sem tampa','Compoteira sem tampa de vidro de pé alto','img/VIDROS/Compoteira-sem-tampa_sNTi1Nm.webp','VIDROS'),
	 ('Saladeira grande Taça','Saladeira em vidro formato em taça grande 5L','img/VIDROS/Saladeira-grande-taca_2NrHJF3.webp','VIDROS'),
	 ('Saladeira de vidro grande','Saladeira com recipiente para gelo','img/VIDROS/Saladeira-vidro-grande_d1WT0go.webp','VIDROS'),
	 ('Prato de bolo Cristal com pé','Prato de bolo cristal com pé tamanho 26x10,5cm de diamêtro.','img/TRAVESSAS/Prato-bolo-cristal-pe.webp','TRAVESSAS'),
	 ('Travessa de Cristal Dragon','Travessa de cristal com pé retangular modelo Dragon.
34,0x15,0x10,5cm','img/TRAVESSAS/Travessa-Cristal-Dragon_oEo9FB7.webp','TRAVESSAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Prato de bolo cristal Janine','Prato de bolo cristal modelo Janine com pé tamanho 29,5x19,5x10,5cm','img/TRAVESSAS/Prato-bolo-cristal-Janine_ZHkOPWF.webp','TRAVESSAS'),
	 ('Travessa baixa de cristal Dragon','Travessa de cristal baixa modelo Dragon. Tamanho: 34,0x15,0x2,5cm','img/TRAVESSAS/Travessa-baixa-cristal-dragon_dWm8arg.webp','TRAVESSAS'),
	 ('Travessa em Inox','Travessa oval de diversos tamanhos de inox 56,45 e 30cm','img/TRAVESSAS/Travessa-inox_XpHsWuC.webp','TRAVESSAS'),
	 ('Travessa Redonda','Travessa redonda de inox com tampa de vidro 4.5L','img/TRAVESSAS/Travessa-redonda_i5l4f7F.webp','TRAVESSAS'),
	 ('Travessa para peixe','Travessa de inox oval para peixada','img/TRAVESSAS/Travessa-peixe_igXn7ks.webp','TRAVESSAS'),
	 ('Travessa de arroz com tampa','Travessa de arroz com tampa de inox','img/TRAVESSAS/Travessa-arroz-tampa_vhnrcDy.webp','TRAVESSAS'),
	 ('Bandeja de garçom','Bandeja de garçom inox de 40cm','img/TRAVESSAS/Bandeja-garcom_YEicGR7.webp','TRAVESSAS'),
	 ('Bandeja redonda rasa','Bandeja redonda rasa em inox','img/TRAVESSAS/Bandeja-redonda-rasa_XHX6LbG.webp','TRAVESSAS'),
	 ('Travessa Redonda','Travessa redonda para biscoito em inox','img/TRAVESSAS/Travessa-redonda-inox_Pw274aG.webp','TRAVESSAS'),
	 ('Bandeja retangular','Bandeja retangular de inox','img/TRAVESSAS/Bandeja-retangular_xHEGbJA.webp','TRAVESSAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Pilter para salada','Pilter para salada em inox','img/TRAVESSAS/Pilter-salada_jXQQsWL.webp','TRAVESSAS'),
	 ('Expositor de 3 bandejas','Expositor com 3 bandejas ajustáveis de vidro','img/TRAVESSAS/Expositor-3-bandejas_v4GGpZK.webp','TRAVESSAS'),
	 ('Bandeja de vidro redonda','Bandeja de vidro redonda com pés em inox diversos tamanhos','img/TRAVESSAS/Bandeja-vidro-redonda_FdyrNEL.webp','TRAVESSAS'),
	 ('Bandeja quadrada de vidro','Bandeja quadrada de vidro com pés em inox diversos tamanhos','img/TRAVESSAS/Bandeja-quadrada-vidro_lQyKLko.webp','TRAVESSAS'),
	 ('Bandeja retangular de vidro','Bandeja retangular de vidro com pés em inox','img/TRAVESSAS/Bandeja-retangular-vidro_8FKmGpD.webp','TRAVESSAS'),
	 ('Bandeja de vidro redonda giratória','Bandeja de vidro redonda giratória','img/TRAVESSAS/Bandeja-vidro-redonda-giratoria_p5J0W9A.webp','TRAVESSAS'),
	 ('Lâmina de vidro redonda','Lâmina redonda de vidro 40cm','img/TRAVESSAS/Lamina-vidro-redonda_OvjfSYb.webp','TRAVESSAS'),
	 ('Travessa de cerâmica','Travessa cerâmica oval 35cm','img/TRAVESSAS/Travessa-ceramica_gul7F4Y.webp','TRAVESSAS'),
	 ('Travessa cerâmica retangular','Travessa cerâmica retangular 35cm','img/TRAVESSAS/Travessa-ceramica-retangular_ex3btdP.webp','TRAVESSAS'),
	 ('Champanheira de mesa','Champanheira para 3 garrafas','img/INOX/Champanheira-de-mesa_bFTtQTT.webp','INOX');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Suporte para balde de champagne','Suporte em inox para balde de champagne','img/INOX/Suporte-para-balde-de-champagne_eg41Kus.webp','INOX'),
	 ('Sopeira','Sopeira em inox 4L','img/INOX/Sopeira_51uUFkV.webp','INOX'),
	 ('Molheira','Molheira em inox','img/INOX/Molheira_CDELInm.webp','INOX'),
	 ('Bowls de Inox','Bowls de inox Grande e Médio','img/INOX/Bowls-de-inox_ymxwgmb.webp','INOX'),
	 ('Petisqueira','Petisqueira em inox com 3 divisões','img/INOX/Petisqueira_9M7M8cm.webp','INOX'),
	 ('Porta guardanapos em inox','Porta guardanapos em inox','img/INOX/Porta-guardanapos_afOROtI.webp','INOX'),
	 ('Mantegueira','Mantegueira em inox','img/INOX/Mantegueira_GiOrSpL.webp','INOX'),
	 ('Bule de café pequeno','Bule de café pequeno','img/INOX/Bule-de-cafe_AxXKGer.webp','INOX'),
	 ('Bule de café grande','Bule de café grande','img/INOX/Bule-de-cafe-grande_dfyA8yp.webp','INOX'),
	 ('Balde de champagne','Balde em inox de champagne','img/INOX/Balde-de-champagne_qRO2J8K.webp','INOX');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Leiteira','Leiteira em inox','img/INOX/Leiteira_FBA3kVL.webp','INOX'),
	 ('Bule de chá','Bule de chá em inox','img/INOX/Bule-de-cha_QlkDahw.webp','INOX'),
	 ('Galheteiro','Galheteiro para azeite e vinagre','img/INOX/Galheteiro_Q8JNssd.webp','INOX'),
	 ('Balde de Gelo','Balde de gelo pequeno em inox','img/INOX/Balde-de-gelo_GduimPV.webp','INOX'),
	 ('Açucareiro','Açucareiro em inox','img/INOX/Acucareiro_CXMdzY1.webp','INOX'),
	 ('Colher Chinesa','Colher para Finger Food de porcelana branca 14cm e 20ml','img/LOUÇAS/Colher-chinesa_jPLjOb9.webp','LOUÇAS'),
	 ('Pote Oriental','Pote oriental quadrado de louþa para mini refeiþ§es 110ml Schimidt. 9,00x3,00cm','img/LOUÇAS/Pote-oriental_wgO8Xcj.webp','LOUÇAS'),
	 ('Tigela golden baixa','Tigela quadrada baixa em louça para mini refeições. 9,00x3,00cm','img/LOUÇAS/Tigela-golden-baixa_FZTTRSl.webp','LOUÇAS'),
	 ('Tigela Retangular com alça','Tigela retangular em louça com alça para mini refeições. 10,5x7,00x2,5cm','img/LOUÇAS/Tigela-retangular-com-alca_JlkUC5I.webp','LOUÇAS'),
	 ('Pote Pirâmide','Pote pirâmide para mini refeições 110ml. 9,00x3,5cm','img/LOUÇAS/Pote-piramide_exJxAhl.webp','LOUÇAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Bowls pequeno de 240ml','Bowl de louça pequeno 240ml','img/LOUÇAS/Bowls-pequeno-240_vwKuLom.webp','LOUÇAS'),
	 ('Copo de caldo de feijão','Copo de louça para caldo de feijão 100ml.','img/LOUÇAS/Copo-caldo-feijao_b3C1ghe.webp','LOUÇAS'),
	 ('Tigela de louça','Tigela de louça branca 400ml.','img/LOUÇAS/Tigela-louca_XaLaNpt.webp','LOUÇAS'),
	 ('Ramequin de louça','Ramequin de louça pequeno 80ml. 4,00cm','img/LOUÇAS/Ramequin-louca_otIGDBh.webp','LOUÇAS'),
	 ('Mantegueira','Mantegueira pequena','img/LOUÇAS/Mantegueira_ziCECvw.webp','LOUÇAS'),
	 ('Sanduicheira de louça','Sanduicheira de louça retangular. 18cm','img/LOUÇAS/Sanduicheira-de-louca_MUxh309.webp','LOUÇAS'),
	 ('Travessa Guarnição','Travessa oval para guarnições pequena. 17cm','img/LOUÇAS/Travessa-guarnicao_lTDg0wd.webp','LOUÇAS'),
	 ('Pote para pastas','Pote de louça para pastas e patê','img/LOUÇAS/Pote-pastas_nK0AEVf.webp','LOUÇAS'),
	 ('Açucareiro em louça','Açucareiro em louça sem colher','img/LOUÇAS/Acucareiro-louca_QlxCovV.webp','LOUÇAS'),
	 ('Petisqueira redonda','Petisqueira de louça redonda','img/LOUÇAS/Petisqueira-redonda_gwv5EzY.webp','LOUÇAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Caneca de vinho','Caneca de vinho de 300ml','img/LOUÇAS/Caneca-vinho_MQvxvHa.jpg','LOUÇAS'),
	 ('Mini caldeirão','Mini caldeirão esmaltado para feijão ou caldos. 500ml','img/LOUÇAS/Mini-caldeirao_VFCcZmK.webp','LOUÇAS'),
	 ('Tigela cerâmica','Tigela cerâmica rústica de 400ml','img/LOUÇAS/Tigela-ceramica_dP2xuKz.webp','LOUÇAS'),
	 ('Xícara de café vera cruz','Xícara de café vera cruz branca simples','img/XÍCARAS/Xicara-cafe-vera-cruz_OfU2Blq.webp','XÍCARAS'),
	 ('Xícara de café friso ouro','Xícara de café friso ouro vera cruz','img/XÍCARAS/Xicara-cafe-friso-ouro_PuwNWy9.webp','XÍCARAS'),
	 ('Xícara de café friso ouro','Xícara de café friso ouro Schimidt','img/XÍCARAS/Xicara-cafe-friso-ouro-schimidt_Go3AHHK.jpg','XÍCARAS'),
	 ('Xícara de chá friso ouro','Xícara de chá friso ouro Schimidt','img/XÍCARAS/Xicara-de-cha-friso-ouro_Ppa4BtD.jpg','XÍCARAS'),
	 ('Xícara de chá friso ouro','Xícara de chá friso ouro com fino acabamento em fio de ouro em sua borda e pires.','img/XÍCARAS/xicara-cha-friso-ouro_bvfRJTX.jpg','XÍCARAS'),
	 ('Xícara de chá 177','Xícara de chá modelo 177 branca simples','img/XÍCARAS/Xicara-de-cha-177_FwOnRDi.jpg','XÍCARAS'),
	 ('Xícara de chá Prisma','Xícara de chá Prisma branca','img/XÍCARAS/Xicara-de-cha-prisma_4j5UCQm.webp','XÍCARAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Bule de café Prisma','Bule de café Schimidt modelo prisma em louça branca com fino acabamento pequeno e grande','img/XÍCARAS/Bule-de-cafe-prisma_8HE7O67.jpg','XÍCARAS'),
	 ('Bule de chá Prisma','Bule de chá  Schimidt modelo prisma em louça branca com fino acabamento','img/XÍCARAS/Bule-de-cha-prisma_SSN0DO6.jpg','XÍCARAS'),
	 ('Açucareiro Prisma','Açucareiro Schimidt modelo prisma em louça branca com fino acabamento.Pequeno e grande','img/XÍCARAS/Acucareiro-prisma_VSIhJHy.jpg','XÍCARAS'),
	 ('Rechaud panela em prata','Rechaud panela em prata 10L','img/PRATARIA/Rechaud-panela-prata_zFxGFDF.webp','PRATARIA'),
	 ('Rechaud Panela em prata','Rechaud panela em prata com banho maria 6L','img/PRATARIA/Rechaud-panela-prata-6L_SMbU2z2.webp','PRATARIA'),
	 ('Rechaud molho em prata','Rechaud para molho em prata 2L','img/PRATARIA/Rechaud-molho-prata_pfB52Zt.webp','PRATARIA'),
	 ('Rechaud chapa de prata','Rechaud chapa retangular de prata sem pirex','img/PRATARIA/Rechaud-chapa-prata_4enUazR.webp','PRATARIA'),
	 ('Travessa oval em prata','Travessa oval em prata 45cm','img/PRATARIA/Travessa-oval-prata_QUfe2ps.webp','PRATARIA'),
	 ('Samovar em prata','Samovar em prata 2L','img/PRATARIA/Samovar-prata_ybJMVWs.webp','PRATARIA'),
	 ('Açucareiro em prata','Açucareiro em prata','img/PRATARIA/Acucareiro-prata_8F9N7mi.webp','PRATARIA');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Bule de café em prata','Bule de café em prata pequeno','img/PRATARIA/Bule-cafe-prata_UbIKss4.webp','PRATARIA'),
	 ('Saladeira Madeira','Saladeira de madeira pequeno e grande','img/MADEIRA/Saladeira-madeira_Zm2EamG.webp','MADEIRA'),
	 ('Tábua de frios grande','Tábua para frios redonda grande 40cm','img/MADEIRA/Tabua-de-frios-grande_EMe8Soz.webp','MADEIRA'),
	 ('Tábua de frios pequena','Tábua para frios redonda pequena 25cm','img/MADEIRA/Tabua-de-frios-pequena_NN1M666.webp','MADEIRA'),
	 ('Tábua pão a metro','Tábua para pão a metro de 80cm','img/MADEIRA/Tabua-pao_94wRjXv.webp','MADEIRA'),
	 ('Tábua de carne oval','Tábua para corte de carne oval','img/MADEIRA/Tabua-carne-oval_1WBrn8y.webp','MADEIRA'),
	 ('Cesta de vime','Cesta de vime para pÒo. Diversos tamanhos','img/MADEIRA/Cesta-vime_Qkk563R.webp','MADEIRA'),
	 ('Cesta de vime com alþa','Cesta de vime para pÒo com alþa grande','img/MADEIRA/Cesta-vime-alca_0sRM8Sg.webp','MADEIRA'),
	 ('Caçarola de alumínio','Caçarola de alumínio Vigor industrial de 30 a 60L','img/PANELAS/Caçarola-de-aluminio_v7UfTRd.webp','PANELAS'),
	 ('Caldeirão de alumínio','Caldeirão de alumínio industrial Vigor de 40 a 65L','img/PANELAS/Caldeirao-de-aluminio.webp','PANELAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Panela de Inox','Caþarola de inox Brinox com capacidade de 8L','img/PANELAS/Panela-de-inox.webp','PANELAS'),
	 ('Panela de cerâmica','Caçarola de cerâmica esmaltada com capacidade de 5L','img/PANELAS/Panela-de-ceramica.webp','PANELAS'),
	 ('Toalha quadrada voal estampada','Toalha quadrada voal estampada','img/TOALHAS/Toalha-quadrada-voal-estampada_HSGcMAi.webp','TOALHAS'),
	 ('Toalha quadrada estampada','Toalha quadrada estampada','img/TOALHAS/Toalha-quadrada-estampada_M04zxFW.webp','TOALHAS'),
	 ('Toalha Branca','Toalha quadrada e redonda branca','img/TOALHAS/Toalha-branca_ZgJBuwV.webp','TOALHAS'),
	 ('Toalha quadrada vermelha','Toalha quadrada vermelha cetim ou tergal','img/TOALHAS/Toalha-quadrada-vermelha_GcjSF9I.webp','TOALHAS'),
	 ('Toalha Preta','Toalha quadrada e pranchÒo preta','img/TOALHAS/Toalha-preta_rpJ9lTO.webp','TOALHAS'),
	 ('Toalha quadrada azul','Toalha quadrada azul','img/TOALHAS/Toalha-azul-quadrada_BkxyVYM.webp','TOALHAS'),
	 ('Toalha ouro','Toalha quadrada e redonda ouro','img/TOALHAS/Toalha-ouro_Xg4mhdr.webp','TOALHAS'),
	 ('Toalha quadrada nude','Toalha quadrada nude cetim','img/TOALHAS/Toalha-quadrada-nude_jwVyu1Z.webp','TOALHAS');
INSERT INTO produtos (nome,descricao,imagem,categoria) VALUES
	 ('Toalha quadrada xadrez verde','Toalha quadrada xadrez verde','img/TOALHAS/Toalha-quadrada-xadrez-verde_MyJDQDs.webp','TOALHAS'),
	 ('Toalha quadrada xadrez azul','Toalha quadrada xadrez azul','img/TOALHAS/Toalha-quadrada-xadrez-azul_051V5Bp.webp','TOALHAS'),
	 ('Tolha quadrada xadrez preta','Toalha quadrada xadrez preta','img/TOALHAS/Toalha-quadrada-xadrez-preta_5FoEhYR.webp','TOALHAS'),
	 ('Toalha quadrada xadrez vermelha','Toalha quadrada xadrez vermelha','img/TOALHAS/Toalha-quadrada-xadrez-vermelha_9M0mDH1.webp','TOALHAS'),
	 ('Toalha quadrada bolinha','Toalha quadrada bolinha','img/TOALHAS/Toalha-quadrada-bolinha_lBSjOcr.webp','TOALHAS'),
	 ('Fogão de alta com 2 bocas','Fogão de alta pressão com pé 80cm de 2 bocas.Acompanha mangueira de alta pressão','img/EQUIPAMENTOS/Fogão-2-bocas_eOGnm4U.webp','EQUIPAMENTOS'),
	 ('Churrasqueira 200L','Churrasqueira de tambor de 200L com grade','img/EQUIPAMENTOS/Churrasqueira_rzvc29T.webp','EQUIPAMENTOS'),
	 ('Tina para bebidas','Tinas para bebidas e gelo 120L','img/EQUIPAMENTOS/Tina-bebidas_V3pIw5D.webp','EQUIPAMENTOS');
